import os
from langchain_tavily import TavilySearch
# The TavilySearch tool will now automatically pick up TAVILY_API_KEY from environment variables
tool = TavilySearch(
    max_results=5,
    topic="general",
    # include_answer=False,
    # include_raw_content=False,
    # include_images=False,
    # include_image_descriptions=False,
    # search_depth="basic",
    # time_range="day",
    # include_domains=None,
    # exclude_domains=None
)

try:
    print("Invoking Tavily tool for Wimbledon query...")
    wimbledon_result = tool.invoke({"query": "What happened at the last wimbledon"})
    print("Wimbledon Search Result (first 400 chars):", wimbledon_result.content[:400])

    print("\nInvoking Tavily tool for Euro 2024 query...")
    # This is usually generated by a model, but we'll create a tool call directly for demo purposes.
    model_generated_tool_call = {
        "args": {"query": "euro 2024 host nation"},
        "id": "1",
        "name": "tavily",
        "type": "tool_call",
    }
    euro_result = tool.invoke(model_generated_tool_call)
    print("Euro 2024 Search Result (first 400 chars):", euro_result.content[:400])

except Exception as e:
    print(f"Error calling TavilySearch tool: {e}")
    print("Please ensure TAVILY_API_KEY is correctly set in Render's environment variables.")